### ISSUE TITLE
IllegalArgumentException (Java): Sheet index (-1) is out of range (0..7)

### ISSUE THREAD

**Issue by 0xD8C4A475** [tamas-ferenci/IrszHnk#1]
```
C:\Program Files\R\R-3.4.3\bin>Rscript.exe IrszHnk.R
Loading required package: XLConnectJars
XLConnect 0.2-14 by Mirai Solutions GmbH [aut],
  Martin Studer [cre],
  The Apache Software Foundation [ctb, cph] (Apache POI),
  Graph Builder [ctb, cph] (Curvesapi Java library)
http://www.mirai-solutions.com
https://github.com/miraisolutions/xlconnect
trying URL 'https://www.posta.hu/static/internet/download/Iranyitoszam-Internet.XLS'
Content type 'application/vnd.ms-excel' length 2598912 bytes (2.5 MB)
==================================================
downloaded 2.5 MB

Error: IllegalArgumentException (Java): Sheet index (-1) is out of range (0..7)
Execution halted
```

Köszi

**Comment by ferenci-tamas** [comment]
(Sorry for replying so late, I wasn't notified of this issue.)

I'm sorry, but I couldn't reproduce this problem! I'd need more details on the architecture you used. Is it possible to try it out under different operating system...?

My best guess is that something is wrong with the download itself, as the reported file size for me is 2598400 bytes. It'd help is you could send me the downloaded file itself. (I.e. after running `download.file( IrszUrl, temp, mode = "wb" )`, the file in `temp`.)

**Comment by ferenci-tamas** [comment]
`XLConnect` is now replaced completely with `rio`.
